---
chapter: "Symbolics"
author: "Daniel Kaplan"
date: 2019-09-27 
version: 0.1
tags: [notes, symbolics, third]
id: puppy-sail-pencil 
---

(ref:puppy-sail-pencil) Exercise in file puppy-sail-pencil

```{r puppy-sail-pencil-default, include = FALSE}
SDSdata::sds_setup()
```

TITLE GOES HERE: Derivatives by manipulating symbols rather than explicit use of the rise-over-run principle.

#### Monomials

-   Derive $\frac{d}{dx} x^2 \rightarrow 2x$ rule by expansion of the definition of derivative.
-   Derive $\frac{d}{dx} x^3 \rightarrow 3x^2$ rule by expansion of the definition of derivative.
-   Show the product rule and how it's consistent with these facts, e.g. break down $x^2$ into $x \times x$ and $x^3$ into $x \times x^2$

-   Work out what the product rule would suggest for $x^4 = x^2 \times x^2 \rightarrow x^2 \times 2 x + 2x \times x^2 = 4x^3$

or $x^4 = x \times x^3 \rightarrow 1 \times x^3 + x \times 3 x^2 = 4 x^3$

-   Ask students to use the product rule (and the previous facts) to deduce what are the derivatives of $x^5, x^6, x^7, x^8$ and, then letting some students assume that $\frac{d}{dx} x^8 = 8 x^7$ ask them to prove up to $x^{16}$.

Product rule. Show the diagram.

#### Exponentials

$2^x, 10^x$, show that you get a scaled version of the exponential. The scale is less than 1 for $2^x$ and greater than 1 for $10^x$. What should be the base such that the scaling factor is exactly 1? That's $e$. 

**Activity**: Ask students to pick a base $B$, say their birthday in the month (2-31) and to apply the definition of the derivative to find, numerically, the derivative $\frac{d}{dx} B^x = \lim_{h \rightarrow 0} \frac{B^{x + h} - B^x}{h}$ -- plot out the function divided by $B^x$ versus $h$ for $h \in c(0,.01)$ -- what value do they get for the constant?

    B = 15
    plotFun( ((B^(x+h)-B^x)/h)/(B^x) ~ h, h=range(0,.01),x=2) # it heads to 2.71 as h-> 0
    log(15)
    [1] 2.708
    B= 43.1
    plotFun( ((B^(x+h)-B^x)/h)/(B^x) ~ h, h=range(0,.01),x=2)
    log(43.1)
    [1] 3.764
    plotFun( ((B^(x+h)-B^x)/h)/(B^x) ~ h, h=range(0,.00001),x=2)

So we end up with a rule: $\frac{d}{dx} B^x = \ln(B) B^x$ A nice base to use is $B s.t. \ln(B) = 1$, that is $B$ is the base of the natural logarithm.

Or, just pick some very small $h$ and look at the multiplier versus \$B\$.

    plotFun( ((B^(x+h)-B^x)/h)/(B^x) ~ B, h=.00001, B=range(2,3),x=2)
    # Find where this crosses 1
    findZeros( ((B^(x+h)-B^x)/h)/(B^x) - 1 ~ B, h=.00001, B=range(2,3),x=2)
    [1] 2.718

#### Chain Rule

Assert the rule.

-   Show that it works with the monomials: $x^6 = (x^3)^2 \rightarrow 2 (x^3) \times 3x^2 = 6 x^5$
-   Show that it works with the exponentials.
    -   Directly from the rule about exponential functions: $e^{kx} = (e^k)^x \rightarrow \ln(e^k) \times (e^k)^x = k e^{kx}$
    -   Via the chain rule: $e^{kx} = e^{g(x)}$ where $g(x) = kx$. So, $\frac{d}{dx} e^{kx} = e^{kx} \times \frac{d}{dx} g(x) = e^{kx} \times k$.

#### Derivative of Logs from Chain Rule

We know $ x = \ln( e^x )$. Differentiate both sides with respect to $x$, giving $ 1 = log'( e^x) e^x$. So $\ln'(e^x) = 1/e^x$. Substitute the symbol $y$ for $e^x$ and you get $\ln'(y) = 1/y$.

#### Now we can do power laws in generality

$x^n = e^{n \ln{x}} \rightarrow n \log'(x) e^{n \ln{x}} = \frac{n}{x} x^n = n x^{n-1}$

#### Flath

-   Differentiation of exponential functions, careful presentation of proportionality between function and its derivative. Log is constant of proportionality
-   Summary of derivative rules: $t^n, a^t, \exp(kt), \sin(at), \cos(at), \ln(t)$, linearity.
-   Wolfram Alpha, in class scavenger hunt beginning with mathematical calculations but extending to data gathering.

Fri Nov 4
---------

#### Review of Differentiation

-   Definition of derivative in terms of rise over run
-   Reading the derivative from a graph
-   Reading the second derivative from a graph
-   Reading partial derivatives from a graph
-   Algebraic rules
    -   $c$
    -   $cf(x)$
    -   $f(x) + g(x)$
    -   $af(x) + bg(x)$
    -   $f(x) g(x)$
    -   $f(g(x))$ -- but first you must be fluent with $f(ax + b)$
    -   $f(x) = x^n$
    -   $f(x) = e^x$
    -   $f(x) = a^x$
    -   $\sin(x), \cos(x)$
    -   $\log(x)$


#### Drill on Power-Law, Exponentials, Polynomials

What sort of function is $a^b$? Depends on whether you are considering $a$ or $b$ as the input.

Chain rule argument to find the derivative $\frac{d}{dx} \ln(x)$

Chain rule argument to find the derivative $\frac{d}{dt} \sin( 2\pi t/P )$

#### Weight of the Great Pyramid

What's the weight of a square pyramid? The [Great Pyramid of Giza](http://en.wikipedia.org/wiki/Great_Pyramid_of_Giza)  is the oldest of the Seven Wonders of the Ancient World.

Height, 146.5 meters (but presently 138.8 meters). Each base side is 230.4 meters. Mass is estimated at 5.9 million tonnes. (There is an internal hillock: volume estimated at 2,500,000 cubic meters. Built of limestone. Density of limestone estimated at 2100 to 2600 kg/cubic-meter.

[Picture of Great Pyramid of Giza, taken by Nina Aldin Thune](http://en.wikipedia.org/wiki/File:Kheops-Pyramid.jpg)


    pyramid.edge = makeFun(230.4*(1 - h/146.5) ~ h)
    pyramid.area =  makeFun( pyramid.edge(h)^2 ~ h )
    PYRAMID.VOLUME = antiD(pyramid.area(h)~h)
    plotFun( PYRAMID.VOLUME(to=h)~h, h=range(0, 146.5))

Question: What's the gravitational potential energy of the stone in the Great Pyramid of Giza?

    g = 9.8 # meters/sec^2
    energy.slice = makeFun(g*2500*h*pyramid.area(h) ~ h)
    ENERGY.SLICE = antiD(energy.slice(h)~h)
    plotFun(ENERGY.SLICE(to=h)~h,h=range(0,146.5) )

Think of this as the total energy needed to build the pyramid, or proportional to that energy, since the people hauling the stones had to haul themselves as well.

The derivative of this can be thought of as the amount of energy needed to raise the pyramid by one meter (meaning, to add one meter of height to the pyramid at different stages of the construction). It's pretty low at the start, since even though there is a lot of area to cover with the stone, the stones don't need to be lifted very high. But near the top of the pyramid, the area is so small that you don't need much energy, even though each block needs to be raised by a lot.

Imagine that you were Moses, or whoever was the contractor for the Great Pyramid of Giza. You've signed a contract with Pharoah saying that you are going to raise the pyramid by 10 cubits each year. You could use this graph -- the derivative, which is the energy.slice function, to figure out how many workers you will need each year. Not so many at first, but then you have to ramp up for the middle of the pyramid, and can lay workers off as you enter into as you enter into the final phases. 

#### Delivery Service Location

Your delivery service is to be located at position 0 along a road. You have a map of the population density along the road. You want to figure out what the average delivery time will be, how much this will cost you, and where you should locate your shop to maximize revenue.

    den = makeFun(dnorm(x,mean=5,sd=1.5)~x)
    plotFun(den(x)~x, x=range(-5,10))
    DEN = antiD(den(x)~x)
    plotFun( DEN(x)~x, x=range(-5,10))
    distfun = makeFun(*den(x)~x, pos=0)
    plotFun(distfun(x)~x, x=range(-5,10))
    plotFun( den(x)~x, add=TRUE, col="red")
    plotFun(5*den(x)~x,add=TRUE,col="red")
    DISTFUN = antiD(distfun(x)~x)
    plotFun(DISTFUN(from=-x,to=x)~x, x=range(-5, 10))

### Lifting an Object into High Orbit

Lifting an object out of Earth's gravitational field. $F = G \frac{m_1 m_2}{r^2}$ where $G = 6.674 \times 10^{-11} N m^2 kg^{-2}$

Mass of the Earth is $5.9737 \times 10^{24}$ kg.

Radius of Earth 6378.1 km

### Integral notation: 

$\int_a^b f(t) dt$. has four parts:
    
#. integral sign. which means sum.
#. differential dt. Which tells you which variable is subdivided.
#. integrand f(t).
#. limits. Which tell you the region that is being subdivided to facilitate the computation.

