---
chapter: "none yet"
title: "Title for bee-write-closet2"
author: "Danny Kaplan"
difficulty: "XX"
output: learnr::tutorial
tutorial:
  id: "bee-write-closet2"
  version: 0.1
runtime: shiny_prerendered
date: 2020-07-04 
tags: [R arithmetic, MMAC textbook, 1.1.7.b]
id: bee-write-closet
---

```{r bee-write-closet2-setup, include = FALSE}
library(etude)
library(learnr)
library(gradethis)

knitr::opts_chunk$set(echo = FALSE)
learnr::tutorial_options(exercise.timelimit = 60, 
                 exercise.checker = gradethis::grade_learnr)
```


`r etude::exercise_title()` Evaluate $$\frac{5 \cdot 6 - 3}{2}$$

```{r bee-write-closet2-E1, exercise=TRUE, exercise.cap="Arithmetic in R", exercise.setup="bee-write-closet2-E1-setup", exercise.eval=FALSE, exercise.lines=2, exercise.completion=FALSE, exercise.startover=TRUE, exercise.diagnostics=TRUE}

```

```{r bee-write-closet2-E1-check}
gradethis::grade_result(
  pass_if( ~ .result == (5 * 6 - 3) / 2),
  fail_if( ~ TRUE, message = "Keep trying!")
)
```


