---
chapter: "Syntax"
title: "Title for cow-talk-piano"
author: "Danny Kaplan"
difficulty: "XX"
output: learnr::tutorial
tutorial:
  id: "cow-talk-piano"
  version: 0.1
runtime: shiny_prerendered
date: 2020-07-05 
tags: [assignment, R syntax, third]
id: cow-talk-piano
---

```{r cow-talk-piano-setup, include = FALSE}
library(etude)
library(learnr)
library(gradethis)

knitr::opts_chunk$set(echo = FALSE)
learnr::tutorial_options(exercise.timelimit = 60, 
                 exercise.checker = gradethis::grade_learnr)
```


`r etude::exercise_title()` Here are three expressions in R. Imagine that they are evaluated one after the other in the order given.

```{r echo=TRUE, results="hide"}
count <- 3
count <- count + 1
count
```

```{r cow-talk-piano-QA1, echo=FALSE}
explain <- "Remember, `<-` is always used to store a value under a name."
etude::choose_one(
  prompt = "A) What is the purpose of the first expression, `count <- 3`?",
  choices = list(
    "To declare that there will be three expressions." = explain,
    "To apply a function `count` to the argument `3`." = explain,
    "+To store the number 3 under the name `count`.+" = ""
  ),
  inline = FALSE
)
```

```{r cow-talk-piano-QA2, echo=FALSE}

etude::choose_one(
  prompt = "B) What is the purpose of the second expression, `count <- count + 1`?",
  choices = list(
    "It has no purpose. There is no such thing as a value that equals itself plus 1." = "The `<-` is not a way of expressing mathematical equality. It performs assignment to a name.",
    "+It increments `count` by 1.+" = "",
    "It replaces the previous value of `count` by the number 1." = "Assignment evaluates the expression on the right-hand side of `<-` and stores it under the name given on the left-hand side. Here, the right-hand side is `count + 1`, not plain `1`."
  ),
  inline = FALSE
)
```



```{r cow-talk-piano-QA3, echo=FALSE}
etude::choose_one(
  prompt = "C) What is the purpose of the expression on the third line of the code box: `count`?",
  choices = list(
    "+To display the value currently stored under the name `count`.+" = "",
    "To reset `count` to 1." = "This would be done with the expression `count <- 1`.",
    "It has no purpose." = "There's no point in having expressions with no purpose!"
  ),
  inline = FALSE
)
```

```{r cow-talk-piano-QA4, echo=FALSE}
etude::choose_one(
  prompt = "D) What will be displayed after the last statement?",
  choices = c(1, 2, 3, "+4+", 5, "There will be no display."),
  random_answer_order = FALSE
)
```

```{etude}
The first expression gives `count` the value 3.

In the second line, the expression to the right of `<-` takes the current value of `count`, namely 3, and adds 1 to it. This value, 4, is then stored under the name `count`, replacing the previous value that had been stored there.

The third expression simply produces the current value of `count`, namely 4.
```




