---
chapter: "none yet"
title: "Title for beech-sleep-drawer"
author: "Danny Kaplan"
output: learnr::tutorial
tutorial:
  id: "beech-sleep-drawer"
  version: 0.1
runtime: shiny_prerendered
date: 2020-06-05 
tags: [contours, slice-plots, wind chill]
id: beech-sleep-drawer
---

```{r beech-sleep-drawer-setup, include = FALSE}
library(etude)
library(learnr)
library(gradethis)
library(ggformula)
library(mosaic)
library(mosaicCalc)
library(math141Z)

knitr::opts_chunk$set(echo = FALSE)
learnr::tutorial_options(exercise.timelimit = 60, 
                 exercise.checker = gradethis::grade_learnr)
```


`r etude::exercise_title()` The graphic below is about wind chill in deg.F, temperature (in deg.F) and wind speed (in mph). 

```{r echo = FALSE}
wind_chill <- function(T_ambient, v_wind) {
  35.74 + 0.6215 * T_ambient - 
    35.75 * v_wind^0.16 + 
    0.4275 * T_ambient * v_wind^0.16
}
contour_plot(wind_chill(T_ambient, v_wind) ~ T_ambient + v_wind,
             domain(T_ambient = c(-50, 20), v_wind = c(6, 30)),
             skip = 0, filled = FALSE, n_contours = 20, 
             contour_color = "gray", label_color = "black") %>%
  gf_labs(title = "Wind Chill (deg F)", y = "Wind velocity (mi/hr)",
          x = "Ambient temperature (deg F)") %>%
  gf_theme(theme_bw())

```




```{r beech-sleep-drawer-C1}
etude::true_or_false(
  "Interpreted as a contour plot, it shows wind chill as a function of temperature and wind speed.",
  TRUE
)
```
 

```{r beech-sleep-drawer-C2}
etude::true_or_false(
  "Interpreted as a series of slice plots it shows wind speed as a function of wind chill and temperature.",
  TRUE
)
```

```{r beech-sleep-drawer-C3}
etude::true_or_false(
  "For a wind speed of 15 and a temperature of 0, the wind chill is appoximately -10.",
  FALSE
)
```

```{r beech-sleep-drawer-C4}
etude::true_or_false(
  "For a wind speed of 30 and a temperature of 20, the wind chill is approximately 0.",
  TRUE
)
```

```{r beech-sleep-drawer-C5}
etude::true_or_false(
  "For a wind *chill* of -40 and a temperature of -20, the wind *speed* is approximately 10.",
  TRUE
)
```

```{r beech-sleep-drawer-C6}
etude::true_or_false(
  "For a wind speed of 20 and a wind chill of 0, the temperature is approximately 0.",
  FALSE
)
```

```{r beech-sleep-drawer-C7}
etude::true_or_false(
  "For a wind speed of 15 and a temperature of 0, the wind chill is approximately -10.",
  FALSE
)
```

```{r beech-sleep-drawer-C8}
etude::true_or_false(
  "For a temperature of 20 and a wind chill of 0, the wind speed is approximately -30.",
  TRUE
)
```

```{r beech-sleep-drawer-C9}
etude::true_or_false(
  "For a wind speed of 10 and a wind chill of -70, the air temperature is approximately -30.",
  FALSE
)
```


