---
chapter: "none yet"
title: "Title for chicken-choose-vase"
author: "Danny Kaplan"
output: learnr::tutorial
tutorial:
  id: "chicken-choose-vase"
  version: 0.1
runtime: shiny_prerendered
date: 2020-06-03 
tags: [first, second, third]
id: chicken-choose-vase
---

```{r chicken-choose-vase-setup, include = FALSE}
library(etude)
library(learnr)
library(gradethis)
library(ggformula)
library(mosaic)
library(mosaicCalc)
library(math141Z)

knitr::opts_chunk$set(echo = FALSE)
learnr::tutorial_options(exercise.timelimit = 60, 
                 exercise.checker = gradethis::grade_learnr)
```


`r etude::exercise_title()` The Bargain Basement store wants to sell its goods quickly.  Consequently, they reduce each product's price $P$ by 5% per day. 

```{r chicken-choose-vase-QA1, echo=FALSE}

etude::choose_one(
  prompt = "If a jacket costs $80 today, how much will it cost in $t$ days?",
  choices = list(
    "$P = 80 - 5t$" = "Remember, 5 percent is exactly the same as 0.05",
    "$P = 80 - 4t$" = "Remember, 4 percent is exactly the same as 0.04",
    "$P = 80 - 0.05t$" = "This  would  be a decrease in  price by 5 cents every day.",
    "$P = 80 (0.05)^t$" = "Each day's price would  be  only 5% that of the previous day's price.",
    "+$P = 80 (0.95)^t$+" = ""
  )
)
```

Here's a sandbox to help  you  do the next  problem.

```{r chicken-choose-vase-sandbox1, exercise=TRUE, exercise.cap="Sandbox for scratch  calculations",  exercise.eval=FALSE, exercise.lines=2, exercise.completion=FALSE, exercise.startover=TRUE, exercise.diagnostics=TRUE}

```
```{r chicken-choose-vase-QA2, echo=FALSE}
etude::choose_one(
  prompt = "You decided that you like the $80 jacket, but you have a budget of only $60. How long should you wait before coming back to the Bargain Basement store.?",
  choices = list(
    "3 days" = "On day 3 the price will be 0.95*0.95*0.95*80. That's above your budget.",
    "4 days" = "On day 4 the price will be $80 \\times 0.95^4$= $65.16. Too much!",
    "5 days" = "On day 5 the price will be $80 \\times 0.95^5$= $61.90. Close, but still higher than your budget.",
    "+6 days+" = ""
  ),
  random_answer_order = FALSE
)
```






