---
chapter: "none yet"
title: "Title for wolf-lead-kitchen"
author: "Danny Kaplan"
output: learnr::tutorial
tutorial:
  id: "wolf-lead-kitchen"
  version: 0.1
runtime: shiny_prerendered
date: 2020-06-03 
tags: [exponentials, parameters, third]
id: wolf-lead-kitchen
---

```{r wolf-lead-kitchen-setup, include = FALSE}
library(etude)
library(learnr)
library(gradethis)
library(ggformula)
library(mosaic)
library(mosaicCalc)
library(math141Z)

knitr::opts_chunk$set(echo = FALSE)
learnr::tutorial_options(exercise.timelimit = 60, 
                 exercise.checker = gradethis::grade_learnr)
```


`r etude::exercise_title()` Rewrite the function $P(t) = 10 (1.7)^{t}$  into the form $P(t) = P_0 \exp{kt}$. 


```{r wolf-lead-kitchen-Qinline1, echo=FALSE}
message <- "Note that $P(t=0) = P_0 e^{k0} = P_0$."
etude::choose_one(
  prompt = "A) In the new form, $P_0$ is which of the following?",
  list("0.531" = message, 
       "5.47" = message, 
       "+10.00+" = "", 
       "15.31" = message, 
       "17" = message),
  random_answer_order = FALSE
)
```

```{r wolf-lead-kitchen-Qinline2, echo=FALSE}
message <- "So that $1.7^t$ will be the same as $e^{kt}$, we must have $k$ such that $e^k$ = 1.7"
etude::choose_one(
  prompt = "B) In the new form, $k$ is which of the following?",
  list("+0.531+"  = '', 
    "5.47" = message, 
    "10.00" = message, 
    "15.31" = message, 
    "17" = message),
  random_answer_order = FALSE
)
```

```{r wolf-lead-kitchen-sandbox1, exercise=TRUE, exercise.cap="Sandbox for scratch work", exercise.setup="document_3db3eaa-sandbox1-setup", exercise.eval=FALSE, exercise.lines=2, exercise.completion=FALSE, exercise.startover=TRUE, exercise.diagnostics=TRUE}

```
